#Setting TheHiveLobbyCore

#Use "\n" to create a new line!
#Use "§" to give color
#item-name for Item Name
#item-cmd for Item Commands

#Color :
#§1 : Dark Blue color
#§2 : Dark Green color
#§3 : Indigo color
#§4 : Red color
#§5 : Purple color
#§6 : Orange color
#§7 : Silver color
#§8 : Dark Gray color
#§9 : Blue color
#§0 : Black color
#§a : Light Green color
#§b : Cloud Blue color
#§c : Red Orange
#§d : Fuhchisia Purple color
#§e : Yellow color
#§f : White color
#§l : Bold the letters

#Items 1 | Compass
item1-name: "§bGame Selector §7[Use]"
item1-cmd: "help"

#Items 2 | Totem Of Undying
item2-name: "§eGlobal Locker §7[Use]"
item2-cmd: "help 2"

#Items 3 | Name Tag
item3-name: "§6Friends §7[Use]"
item3-cmd: "help 3"

#Items 4 | Enchanted Book
item4-name: "§aParty §7[Use]"
item4-cmd: "about TheHiveLobbyCore"

#Author : DrelezTM
